version: "3.9"
   
services:
  db:
    build: .
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - POSTGRES_DB=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    container_name: db

  pghero:
    image: ankane/pghero
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    container_name: pghero

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
    env_file:
      - .env
    container_name: web

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
