# Generated by Django 3.1.14 on 2022-08-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='user',
        ),
    ]
